$axure.loadCurrentPage({
  "url":"已领取过弹窗.html",
  "generationDate":new Date(1461742325145.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5ce43b92feaf40e981dcf2ca898c4194",
    "type":"Axure:Page",
    "name":"已领取过弹窗",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e67a4bb6c4a04c1e96654d0eb36f8abf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":20},
            "size":{
              "width":300,
              "height":530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9d35d207e86b4e0baa253ab818e13d84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":20},
                "size":{
                  "width":300,
                  "height":530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加载页/u0.png"}},
{
          "id":"735a41105e76485aa299d8402b997956",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":470},
            "size":{
              "width":200,
              "height":40},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ffa3f19c974422685e9268529b260c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":470},
                "size":{
                  "width":200,
                  "height":40},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领券页面/u14.png"}},
{
          "id":"fa2b4300bfb74bab85cfe409a47c7038",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":99,
              "y":90},
            "size":{
              "width":282,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"89ab330dbf7f4ffbb34f48a28c4680e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99,
                  "y":90},
                "size":{
                  "width":282,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取成功弹窗/u4.png"}},
{
          "id":"f8c11f4758ef4959bf061996f67b2ed0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":135.5,
              "y":360},
            "size":{
              "width":209,
              "height":40},
            "cornerRadiusTopLeft":"54"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"916973eb9dc34151b1c96f6f6cb56053",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":135.5,
                  "y":360},
                "size":{
                  "width":209,
                  "height":40},
                "cornerRadiusTopLeft":"54"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 下载页面",
                      "target":{
                        "targetType":"page",
                        "url":"下载页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/领取成功弹窗/u10.png"}},
{
          "id":"c242e987ad6e4334bcbc0867d8f57d4c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":155,
              "y":141},
            "size":{
              "width":169,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7dc2091cb4af446eb1e797b601bd75e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":155,
                  "y":141},
                "size":{
                  "width":169,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"026534bc922f4c108327ca5c2e58e14e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":121,
              "y":225},
            "size":{
              "width":260,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"828600bc306a498e9e57090478c24b1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":121,
                  "y":225},
                "size":{
                  "width":260,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be873ce71d75458c829a4e34a73cd95f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":420},
            "size":{
              "width":209,
              "height":40},
            "cornerRadiusTopLeft":"54"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1abafac2d405421ebcbc8dfb6455873c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":420},
                "size":{
                  "width":209,
                  "height":40},
                "cornerRadiusTopLeft":"54"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 分享至朋友圈",
                      "target":{
                        "targetType":"page",
                        "url":"分享至朋友圈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/领取成功弹窗/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e67a4bb6c4a04c1e96654d0eb36f8abf":{
      "scriptId":"u0"},
    "9d35d207e86b4e0baa253ab818e13d84":{
      "scriptId":"u1"},
    "735a41105e76485aa299d8402b997956":{
      "scriptId":"u2"},
    "0ffa3f19c974422685e9268529b260c6":{
      "scriptId":"u3"},
    "fa2b4300bfb74bab85cfe409a47c7038":{
      "scriptId":"u4"},
    "89ab330dbf7f4ffbb34f48a28c4680e8":{
      "scriptId":"u5"},
    "f8c11f4758ef4959bf061996f67b2ed0":{
      "scriptId":"u6"},
    "916973eb9dc34151b1c96f6f6cb56053":{
      "scriptId":"u7"},
    "c242e987ad6e4334bcbc0867d8f57d4c":{
      "scriptId":"u8"},
    "7dc2091cb4af446eb1e797b601bd75e2":{
      "scriptId":"u9"},
    "026534bc922f4c108327ca5c2e58e14e":{
      "scriptId":"u10"},
    "828600bc306a498e9e57090478c24b1f":{
      "scriptId":"u11"},
    "be873ce71d75458c829a4e34a73cd95f":{
      "scriptId":"u12"},
    "1abafac2d405421ebcbc8dfb6455873c":{
      "scriptId":"u13"}}});