$axure.loadCurrentPage({
  "url":"领券页面.html",
  "generationDate":new Date(1461742325034.68),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9bd044715f1e4f9c8a43c2254255f1c3",
    "type":"Axure:Page",
    "name":"领券页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"82f557a3731c46f89abff1de52a8d24b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90.5,
              "y":20},
            "size":{
              "width":300,
              "height":530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7baeb6ee9d724511b58a4e6009509d67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90.5,
                  "y":20},
                "size":{
                  "width":300,
                  "height":530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加载页/u0.png"}},
{
          "id":"a65ef0db64114550b2d60742baff939e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"28px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":129,
              "y":60},
            "size":{
              "width":222,
              "height":65}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bb98299d5e94519a015ba697ac48fdf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"28px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":129,
                  "y":60},
                "size":{
                  "width":222,
                  "height":65}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"957cb576dd784325aff2ed0cb304b0ee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":106,
              "y":125},
            "size":{
              "width":264,
              "height":155}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"33b2d73bc4584c519d9bf9491aa47f05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":106,
                  "y":125},
                "size":{
                  "width":264,
                  "height":155}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领券页面/u4.png"}},
{
          "id":"60ac196a610745c9be87576ed83ea6a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":111,
              "y":160},
            "size":{
              "width":259,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73fc2e7a4f99492fa34a9b4349d69b92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":111,
                  "y":160},
                "size":{
                  "width":259,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae954b4ceca641a49365f0685d0a9a66",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":300},
            "size":{
              "width":242,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8dda9b226ba64f30baa650eca419f81a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":300},
                "size":{
                  "width":242,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领券页面/u8.png"}},
{
          "id":"39dfd85919134eed894b582d1b642cca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":117,
              "y":370},
            "size":{
              "width":160,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"754adad988584b39bee24dec0042d5c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":117,
                  "y":370},
                "size":{
                  "width":160,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领券页面/u10.png"}},
{
          "id":"6efc7bdf8fce4748bd0234c87759195b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":370},
            "size":{
              "width":65,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a83a8a4a771240b5bfcecd91e640611d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":294,
                  "y":370},
                "size":{
                  "width":65,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领券页面/u12.png"}},
{
          "id":"2d9b9e5873b14dc48a83b2d4cfb69a7e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":470},
            "size":{
              "width":200,
              "height":40},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30a81e463c404a4d96c7c0a924267689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":470},
                "size":{
                  "width":200,
                  "height":40},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 领取成功弹窗",
                      "target":{
                        "targetType":"page",
                        "url":"领取成功弹窗.html",
                        "includeVariables":true},
                      "linkType":"current"}]},
{
                  "description":"用例 2",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 已领取过弹窗",
                      "target":{
                        "targetType":"page",
                        "url":"已领取过弹窗.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/领券页面/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "82f557a3731c46f89abff1de52a8d24b":{
      "scriptId":"u0"},
    "7baeb6ee9d724511b58a4e6009509d67":{
      "scriptId":"u1"},
    "a65ef0db64114550b2d60742baff939e":{
      "scriptId":"u2"},
    "0bb98299d5e94519a015ba697ac48fdf":{
      "scriptId":"u3"},
    "957cb576dd784325aff2ed0cb304b0ee":{
      "scriptId":"u4"},
    "33b2d73bc4584c519d9bf9491aa47f05":{
      "scriptId":"u5"},
    "60ac196a610745c9be87576ed83ea6a8":{
      "scriptId":"u6"},
    "73fc2e7a4f99492fa34a9b4349d69b92":{
      "scriptId":"u7"},
    "ae954b4ceca641a49365f0685d0a9a66":{
      "scriptId":"u8"},
    "8dda9b226ba64f30baa650eca419f81a":{
      "scriptId":"u9"},
    "39dfd85919134eed894b582d1b642cca":{
      "scriptId":"u10"},
    "754adad988584b39bee24dec0042d5c6":{
      "scriptId":"u11"},
    "6efc7bdf8fce4748bd0234c87759195b":{
      "scriptId":"u12"},
    "a83a8a4a771240b5bfcecd91e640611d":{
      "scriptId":"u13"},
    "2d9b9e5873b14dc48a83b2d4cfb69a7e":{
      "scriptId":"u14"},
    "30a81e463c404a4d96c7c0a924267689":{
      "scriptId":"u15"}}});