$axure.loadCurrentPage({
  "url":"未碰上炸弹，游戏结束弹窗.html",
  "generationDate":new Date(1461742324940.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4fa79de2bb09413aacdc9338ff337657",
    "type":"Axure:Page",
    "name":"未碰上炸弹，游戏结束弹窗",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4427d455503f4c3ca68e507c609678ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":20},
            "size":{
              "width":300,
              "height":530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b42a07467a6647be93ff23de18888670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":20},
                "size":{
                  "width":300,
                  "height":530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加载页/u0.png"}},
{
          "id":"213a5aae2fca49c0a4db37bd775d8126",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":30},
            "size":{
              "width":260,
              "height":22},
            "cornerRadiusTopLeft":"48"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e0095a507fa495faf18ba00ced53cc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":260,
                  "height":22},
                "cornerRadiusTopLeft":"48"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u4.png"}},
{
          "id":"b5bf3cff90764bc39e0b8de1e77c24a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":76},
            "size":{
              "width":80,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"60f6d14132434a409dd12a775639a6d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":76},
                "size":{
                  "width":80,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未碰上炸弹，游戏结束弹窗/u4.jpg"}},
{
          "id":"4dee788e885c4b1e94b2d77da3e07090",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":170},
            "size":{
              "width":70,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07543fca084e49558f9439115a24e8a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":170},
                "size":{
                  "width":70,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u10.jpg"}},
{
          "id":"076b7aee0a85412489c9cf2ee4883b5d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":116},
            "size":{
              "width":80,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aa8b991b3ce4e0bbfc34cb7e46968d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":116},
                "size":{
                  "width":80,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未碰上炸弹，游戏结束弹窗/u4.jpg"}},
{
          "id":"213065fa19cd4bba9f0f7bf29d21e5fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":200},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f3bdf8e889b45958b424b417df0387f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":200},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u12.jpg"}},
{
          "id":"80d12f91bb6d43cdae6152fd5c1f8cba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":270},
            "size":{
              "width":80,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce75cb0fe9bf453bb35fc7f597b7fa38",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":270},
                "size":{
                  "width":80,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未碰上炸弹，游戏结束弹窗/u4.jpg"}},
{
          "id":"ec9479ab30ff45bb94deec175736b6e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":360},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf96b8c627cf4d42a11ab636efd4e7ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":360},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u12.jpg"}},
{
          "id":"fb1173895fb94c679979c2800d734019",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":241,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75aa56c68651421489b31678a07b288c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":241,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未碰上炸弹，游戏结束弹窗/u16.png"}},
{
          "id":"6147c7fd13824678b472cff2487fc6ee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":136,
              "y":144},
            "size":{
              "width":170,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b873a1b85df429daeade3e9fc827cb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":136,
                  "y":144},
                "size":{
                  "width":170,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec64002a58514b618589e2cc37325836",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":160,
              "y":224},
            "size":{
              "width":119,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cd490fe85554200a1d6f3a30ab93c09",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":160,
                  "y":224},
                "size":{
                  "width":119,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未碰上炸弹，游戏结束弹窗/u20.png"}},
{
          "id":"c21cc08312994a2e8807b63916916631",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":110,
              "y":385},
            "size":{
              "width":221,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1137ed62c6a4a7f9e3e3893ba1201aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":110,
                  "y":385},
                "size":{
                  "width":221,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a76adff45ab4031a82f80692226f43b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":416},
            "size":{
              "width":165,
              "height":34},
            "cornerRadiusTopLeft":"66"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"311b583069164507a6ad70964678fe40",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":416},
                "size":{
                  "width":165,
                  "height":34},
                "cornerRadiusTopLeft":"66"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 领券页面",
                      "target":{
                        "targetType":"page",
                        "url":"领券页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/未碰上炸弹，游戏结束弹窗/u24.png"}},
{
          "id":"48d2e99c4456476ab137fa6838d82a55",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":141,
              "y":460},
            "size":{
              "width":165,
              "height":34},
            "cornerRadiusTopLeft":"66"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b931a591a584a648f3e012c8f283dfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":141,
                  "y":460},
                "size":{
                  "width":165,
                  "height":34},
                "cornerRadiusTopLeft":"66"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 分享至朋友圈",
                      "target":{
                        "targetType":"page",
                        "url":"分享至朋友圈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/未碰上炸弹，游戏结束弹窗/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "4427d455503f4c3ca68e507c609678ec":{
      "scriptId":"u0"},
    "b42a07467a6647be93ff23de18888670":{
      "scriptId":"u1"},
    "213a5aae2fca49c0a4db37bd775d8126":{
      "scriptId":"u2"},
    "6e0095a507fa495faf18ba00ced53cc1":{
      "scriptId":"u3"},
    "b5bf3cff90764bc39e0b8de1e77c24a8":{
      "scriptId":"u4"},
    "60f6d14132434a409dd12a775639a6d0":{
      "scriptId":"u5"},
    "4dee788e885c4b1e94b2d77da3e07090":{
      "scriptId":"u6"},
    "07543fca084e49558f9439115a24e8a5":{
      "scriptId":"u7"},
    "076b7aee0a85412489c9cf2ee4883b5d":{
      "scriptId":"u8"},
    "7aa8b991b3ce4e0bbfc34cb7e46968d9":{
      "scriptId":"u9"},
    "213065fa19cd4bba9f0f7bf29d21e5fc":{
      "scriptId":"u10"},
    "8f3bdf8e889b45958b424b417df0387f":{
      "scriptId":"u11"},
    "80d12f91bb6d43cdae6152fd5c1f8cba":{
      "scriptId":"u12"},
    "ce75cb0fe9bf453bb35fc7f597b7fa38":{
      "scriptId":"u13"},
    "ec9479ab30ff45bb94deec175736b6e3":{
      "scriptId":"u14"},
    "cf96b8c627cf4d42a11ab636efd4e7ec":{
      "scriptId":"u15"},
    "fb1173895fb94c679979c2800d734019":{
      "scriptId":"u16"},
    "75aa56c68651421489b31678a07b288c":{
      "scriptId":"u17"},
    "6147c7fd13824678b472cff2487fc6ee":{
      "scriptId":"u18"},
    "1b873a1b85df429daeade3e9fc827cb9":{
      "scriptId":"u19"},
    "ec64002a58514b618589e2cc37325836":{
      "scriptId":"u20"},
    "2cd490fe85554200a1d6f3a30ab93c09":{
      "scriptId":"u21"},
    "c21cc08312994a2e8807b63916916631":{
      "scriptId":"u22"},
    "f1137ed62c6a4a7f9e3e3893ba1201aa":{
      "scriptId":"u23"},
    "3a76adff45ab4031a82f80692226f43b":{
      "scriptId":"u24"},
    "311b583069164507a6ad70964678fe40":{
      "scriptId":"u25"},
    "48d2e99c4456476ab137fa6838d82a55":{
      "scriptId":"u26"},
    "7b931a591a584a648f3e012c8f283dfa":{
      "scriptId":"u27"}}});