$axure.loadCurrentPage({
  "url":"游戏页面.html",
  "generationDate":new Date(1461742324872.58),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"acf9c90440ed43af9d412bc7c437f385",
    "type":"Axure:Page",
    "name":"游戏页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c1b5703197244726946342ea61cb40ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":20},
            "size":{
              "width":300,
              "height":530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1153e81a29d4228a24d12d0ef365623",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":20},
                "size":{
                  "width":300,
                  "height":530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加载页/u0.png"}},
{
          "id":"5bc1ce4e82ef4883aa0168fc30c8281e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":30},
            "size":{
              "width":62,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c13b401d7ce411098d7857e82d290ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":134,
                  "y":30},
                "size":{
                  "width":62,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"24c3b80f4ad74c1ca176de36737fa041",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":30},
            "size":{
              "width":260,
              "height":22},
            "cornerRadiusTopLeft":"48"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1ca7885469d47f59a5e0b38b5e07568",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":260,
                  "height":22},
                "cornerRadiusTopLeft":"48"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u4.png"}},
{
          "id":"d97b76e34a5045bfb283e3e4d32caa8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":149,
              "y":35},
            "size":{
              "width":52,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03dbdc011b1440b1b3971360e98ee2be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":149,
                  "y":35},
                "size":{
                  "width":52,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ba760fcf32d4446ba562cd8e81fc3b9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":220},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51ae5501dd7942ab92c3170cf136db5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":220},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u8.jpg"}},
{
          "id":"3998285ba24c4e1abb22c562337dfc82",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":160},
            "size":{
              "width":70,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10530887288d493696c93511aee78a7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":181,
                  "y":160},
                "size":{
                  "width":70,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u10.jpg"}},
{
          "id":"b4d8f6c81e7648b299edd2d8b5725476",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":210},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cfddc76abaf4e1a83f518d2f85adf92",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275,
                  "y":210},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u12.jpg"}},
{
          "id":"db015e1858854e4aa15400275a0a45f4",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":273},
            "size":{
              "width":73,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb7f9de98174424c82d5c9384f0ec8cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202,
                  "y":273},
                "size":{
                  "width":73,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u14.png"}},
{
          "id":"0ed8f73236454295be180434362a02d7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":304},
            "size":{
              "width":70,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bcd557248bf401781be86dd336386ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":304},
                "size":{
                  "width":70,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u10.jpg"}},
{
          "id":"1e7a8657836b494f896a856258a2e439",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":181,
              "y":440},
            "size":{
              "width":115,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75f048f8dcc04ebf9373ffd27f9bfb22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":181,
                  "y":440},
                "size":{
                  "width":115,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u18.png"}},
{
          "id":"326dcdc77810471d8142d5f231f2a876",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":100},
            "size":{
              "width":73,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b8c93707b844cc7ba3df6c4dbcbceb4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":100},
                "size":{
                  "width":73,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u14.png"}},
{
          "id":"ad3eb54deeab480c97e8b65dc90256fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":287,
              "y":73},
            "size":{
              "width":73,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baca953d45d748f293109f2286d4aabc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":287,
                  "y":73},
                "size":{
                  "width":73,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c1b5703197244726946342ea61cb40ae":{
      "scriptId":"u0"},
    "a1153e81a29d4228a24d12d0ef365623":{
      "scriptId":"u1"},
    "5bc1ce4e82ef4883aa0168fc30c8281e":{
      "scriptId":"u2"},
    "7c13b401d7ce411098d7857e82d290ba":{
      "scriptId":"u3"},
    "24c3b80f4ad74c1ca176de36737fa041":{
      "scriptId":"u4"},
    "a1ca7885469d47f59a5e0b38b5e07568":{
      "scriptId":"u5"},
    "d97b76e34a5045bfb283e3e4d32caa8a":{
      "scriptId":"u6"},
    "03dbdc011b1440b1b3971360e98ee2be":{
      "scriptId":"u7"},
    "4ba760fcf32d4446ba562cd8e81fc3b9":{
      "scriptId":"u8"},
    "51ae5501dd7942ab92c3170cf136db5d":{
      "scriptId":"u9"},
    "3998285ba24c4e1abb22c562337dfc82":{
      "scriptId":"u10"},
    "10530887288d493696c93511aee78a7c":{
      "scriptId":"u11"},
    "b4d8f6c81e7648b299edd2d8b5725476":{
      "scriptId":"u12"},
    "2cfddc76abaf4e1a83f518d2f85adf92":{
      "scriptId":"u13"},
    "db015e1858854e4aa15400275a0a45f4":{
      "scriptId":"u14"},
    "cb7f9de98174424c82d5c9384f0ec8cb":{
      "scriptId":"u15"},
    "0ed8f73236454295be180434362a02d7":{
      "scriptId":"u16"},
    "0bcd557248bf401781be86dd336386ef":{
      "scriptId":"u17"},
    "1e7a8657836b494f896a856258a2e439":{
      "scriptId":"u18"},
    "75f048f8dcc04ebf9373ffd27f9bfb22":{
      "scriptId":"u19"},
    "326dcdc77810471d8142d5f231f2a876":{
      "scriptId":"u20"},
    "7b8c93707b844cc7ba3df6c4dbcbceb4":{
      "scriptId":"u21"},
    "ad3eb54deeab480c97e8b65dc90256fc":{
      "scriptId":"u22"},
    "baca953d45d748f293109f2286d4aabc":{
      "scriptId":"u23"}}});