$axure.loadCurrentPage({
  "url":"碰上炸弹，游戏结束弹窗.html",
  "generationDate":new Date(1461742324983.66),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"77183ce5ea09428090813e73150da8d4",
    "type":"Axure:Page",
    "name":"碰上炸弹，游戏结束弹窗",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"126f83163e39446f9dfc34c232a5a58a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":20},
            "size":{
              "width":300,
              "height":530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27065492c1944362814e0a01a4f8de7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":20},
                "size":{
                  "width":300,
                  "height":530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加载页/u0.png"}},
{
          "id":"017d2494ed404e4d93661e0a6149dd09",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":30},
            "size":{
              "width":260,
              "height":22},
            "cornerRadiusTopLeft":"48"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79ef27c0f8e3431a9c89ee9efdd9319e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":260,
                  "height":22},
                "cornerRadiusTopLeft":"48"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u4.png"}},
{
          "id":"41fc4d7519914ee1820fc6a27437c7c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":76},
            "size":{
              "width":80,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b67171da27264df68becf6829a715104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":76},
                "size":{
                  "width":80,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未碰上炸弹，游戏结束弹窗/u4.jpg"}},
{
          "id":"33af795c25fb4a20a8558750c2c75504",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":170},
            "size":{
              "width":70,
              "height":86}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c731940bf69a4bde89f826aaf5232938",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":170},
                "size":{
                  "width":70,
                  "height":86}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u10.jpg"}},
{
          "id":"423236f8b5b74a59afcecf7a8b3cce22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":200},
            "size":{
              "width":90,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc73ff1f7dd0419984cfab4e3397f3d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":200},
                "size":{
                  "width":90,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/游戏页面/u12.jpg"}},
{
          "id":"1c63f0d49fc1492ea048b97b1c203c23",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":99.5,
              "y":100},
            "size":{
              "width":241,
              "height":416}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36aa3ccce91d4e17bfc4381a904af761",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":99.5,
                  "y":100},
                "size":{
                  "width":241,
                  "height":416}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未碰上炸弹，游戏结束弹窗/u16.png"}},
{
          "id":"da48b7fb4ad54e348e7a97a9c733d7b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":144,
              "y":140},
            "size":{
              "width":172,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bfb7ce040334cabb40142b03cc41382",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":144,
                  "y":140},
                "size":{
                  "width":172,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"737aed9437614af1a1a8630b129a4ba9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":210},
            "size":{
              "width":120,
              "height":137}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74073d08dc8a4dcfa0dfa42dc627c230",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":210},
                "size":{
                  "width":120,
                  "height":137}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/碰上炸弹，游戏结束弹窗/u14.png"}},
{
          "id":"2090611a44af41c18d6d00cc64707e73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":106,
              "y":357},
            "size":{
              "width":224,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84ef85febf004d7988e11e9996b00955",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":106,
                  "y":357},
                "size":{
                  "width":224,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af186ca05a9a4a51b95b30b2247a5146",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":430},
            "size":{
              "width":165,
              "height":34},
            "cornerRadiusTopLeft":"66"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9669e4c4b154362971e01f563619d25",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":430},
                "size":{
                  "width":165,
                  "height":34},
                "cornerRadiusTopLeft":"66"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 领券页面",
                      "target":{
                        "targetType":"page",
                        "url":"领券页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/未碰上炸弹，游戏结束弹窗/u24.png"}},
{
          "id":"2d279a01b7384c1a94c943ea5e9821bd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":144,
              "y":474},
            "size":{
              "width":165,
              "height":34},
            "cornerRadiusTopLeft":"66"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ba1e2d590504b4e8890a4f1dd0e7612",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":144,
                  "y":474},
                "size":{
                  "width":165,
                  "height":34},
                "cornerRadiusTopLeft":"66"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页",
                      "target":{
                        "targetType":"page",
                        "url":"首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/未碰上炸弹，游戏结束弹窗/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "126f83163e39446f9dfc34c232a5a58a":{
      "scriptId":"u0"},
    "27065492c1944362814e0a01a4f8de7f":{
      "scriptId":"u1"},
    "017d2494ed404e4d93661e0a6149dd09":{
      "scriptId":"u2"},
    "79ef27c0f8e3431a9c89ee9efdd9319e":{
      "scriptId":"u3"},
    "41fc4d7519914ee1820fc6a27437c7c2":{
      "scriptId":"u4"},
    "b67171da27264df68becf6829a715104":{
      "scriptId":"u5"},
    "33af795c25fb4a20a8558750c2c75504":{
      "scriptId":"u6"},
    "c731940bf69a4bde89f826aaf5232938":{
      "scriptId":"u7"},
    "423236f8b5b74a59afcecf7a8b3cce22":{
      "scriptId":"u8"},
    "dc73ff1f7dd0419984cfab4e3397f3d3":{
      "scriptId":"u9"},
    "1c63f0d49fc1492ea048b97b1c203c23":{
      "scriptId":"u10"},
    "36aa3ccce91d4e17bfc4381a904af761":{
      "scriptId":"u11"},
    "da48b7fb4ad54e348e7a97a9c733d7b1":{
      "scriptId":"u12"},
    "9bfb7ce040334cabb40142b03cc41382":{
      "scriptId":"u13"},
    "737aed9437614af1a1a8630b129a4ba9":{
      "scriptId":"u14"},
    "74073d08dc8a4dcfa0dfa42dc627c230":{
      "scriptId":"u15"},
    "2090611a44af41c18d6d00cc64707e73":{
      "scriptId":"u16"},
    "84ef85febf004d7988e11e9996b00955":{
      "scriptId":"u17"},
    "af186ca05a9a4a51b95b30b2247a5146":{
      "scriptId":"u18"},
    "c9669e4c4b154362971e01f563619d25":{
      "scriptId":"u19"},
    "2d279a01b7384c1a94c943ea5e9821bd":{
      "scriptId":"u20"},
    "1ba1e2d590504b4e8890a4f1dd0e7612":{
      "scriptId":"u21"}}});