$axure.loadCurrentPage({
  "url":"领取成功弹窗.html",
  "generationDate":new Date(1461742325105.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"92616ba01f994969ae18779a858fd999",
    "type":"Axure:Page",
    "name":"领取成功弹窗",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0915d8abffd64a35a83024b6cd1a43a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":20},
            "size":{
              "width":300,
              "height":530}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28db0d82399e4c93bea204d2748ad8aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":20},
                "size":{
                  "width":300,
                  "height":530}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/加载页/u0.png"}},
{
          "id":"3234a6636aef48af93e70b6abaf2ccd8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":470},
            "size":{
              "width":200,
              "height":40},
            "cornerRadiusTopLeft":"100"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2f9814820524768a03a33ce329196bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":470},
                "size":{
                  "width":200,
                  "height":40},
                "cornerRadiusTopLeft":"100"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领券页面/u14.png"}},
{
          "id":"117887dd6d094332bb432e8040919c8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":98,
              "y":90},
            "size":{
              "width":282,
              "height":410}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85da538792a54897a72188c220569f32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":98,
                  "y":90},
                "size":{
                  "width":282,
                  "height":410}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/领取成功弹窗/u4.png"}},
{
          "id":"0dd978be242548c39d2af1b7afaec3b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"700",
            "horizontalAlignment":"center",
            "location":{
              "x":132,
              "y":130},
            "size":{
              "width":217,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2f9aa48e05f4d7ca79152c24a74037a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"700",
                "horizontalAlignment":"center",
                "location":{
                  "x":132,
                  "y":130},
                "size":{
                  "width":217,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25c0c3fb0632434a94e57e175475ff68",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"22px",
            "location":{
              "x":110,
              "y":233},
            "size":{
              "width":260,
              "height":147}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69cc3aed314a4f9f9db8437e43a44eea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"22px",
                "location":{
                  "x":110,
                  "y":233},
                "size":{
                  "width":260,
                  "height":147}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d222a9bd76af44b7b818ce7741a40773",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":360},
            "size":{
              "width":209,
              "height":40},
            "cornerRadiusTopLeft":"54"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47de33f08beb4b12a40a68a40ab46b01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":360},
                "size":{
                  "width":209,
                  "height":40},
                "cornerRadiusTopLeft":"54"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 下载页面",
                      "target":{
                        "targetType":"page",
                        "url":"下载页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/领取成功弹窗/u10.png"}},
{
          "id":"666817be2f934c3c93c9275bcc366f4a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":131,
              "y":420},
            "size":{
              "width":209,
              "height":40},
            "cornerRadiusTopLeft":"54"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05cc9c382a9b4240b65c4ec23506acc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":131,
                  "y":420},
                "size":{
                  "width":209,
                  "height":40},
                "cornerRadiusTopLeft":"54"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 分享至朋友圈",
                      "target":{
                        "targetType":"page",
                        "url":"分享至朋友圈.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/领取成功弹窗/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "0915d8abffd64a35a83024b6cd1a43a3":{
      "scriptId":"u0"},
    "28db0d82399e4c93bea204d2748ad8aa":{
      "scriptId":"u1"},
    "3234a6636aef48af93e70b6abaf2ccd8":{
      "scriptId":"u2"},
    "e2f9814820524768a03a33ce329196bd":{
      "scriptId":"u3"},
    "117887dd6d094332bb432e8040919c8a":{
      "scriptId":"u4"},
    "85da538792a54897a72188c220569f32":{
      "scriptId":"u5"},
    "0dd978be242548c39d2af1b7afaec3b9":{
      "scriptId":"u6"},
    "e2f9aa48e05f4d7ca79152c24a74037a":{
      "scriptId":"u7"},
    "25c0c3fb0632434a94e57e175475ff68":{
      "scriptId":"u8"},
    "69cc3aed314a4f9f9db8437e43a44eea":{
      "scriptId":"u9"},
    "d222a9bd76af44b7b818ce7741a40773":{
      "scriptId":"u10"},
    "47de33f08beb4b12a40a68a40ab46b01":{
      "scriptId":"u11"},
    "666817be2f934c3c93c9275bcc366f4a":{
      "scriptId":"u12"},
    "05cc9c382a9b4240b65c4ec23506acc8":{
      "scriptId":"u13"}}});